apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nodejs2
  labels:
    app: example-nodejs2
spec:
  selector:
    matchLabels:
      app: example-nodejs2
  template:
    metadata:
      labels:
        app: example-nodejs2
    spec:
      containers:
        - name: example-nodejs2
          image: example-nodejs-image2
          ports:
            - containerPort: 8000
